In [2]:
import numpy as np
from sklearn.datasets import load_diabetes


In [3]:
#extract x,y from a sklearn dataset

In [5]:
X,y =load_diabetes(return_X_y=True)

In [6]:
X


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [9]:
y.shape


(442,)

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=3)

<h1>Using Sklearn</h1>

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
reg=LinearRegression()

In [15]:
reg.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [16]:
y_pred=reg.predict(X_test)

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score (y_test,y_pred)

0.4161792211496943

In [19]:
reg.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [20]:
reg.intercept_

np.float64(153.13441535285003)

<h1>My making a own class</h1>

In [45]:
class LR:
    def __init__(self):
        self.coef=None
        self.intercept=None
    def fit(self,X_train,y_train):
        X_train =np.insert(X_train,0,1,axis=1)

        #calculate the coef
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept=betas[0]
        self.coef=betas[1:]
        print(betas)
        
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef)+self.intercept
        return y_pred
        
        
    
        

In [46]:
lr=LR()

In [47]:
lr.fit(X_train,y_train)

[ 153.13441535   -1.13744712 -212.8867836   540.45536994  345.20621542
 -938.23814645  516.62060367  172.85885498  267.87535242  732.63230159
   70.07849485]


In [48]:
X_train.shape

(353, 10)

In [49]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [51]:
y_pred=lr.predict(X_test)

In [53]:
y_pred

array([ 99.48235947, 181.25429903, 106.61572846, 123.10541923,
       183.04909567,  83.29913847, 130.54854188, 233.85654301,
       155.00942627, 171.46626454, 171.06003791, 192.94190885,
       147.25129841, 214.5307459 ,  47.50252863, 142.43786422,
       119.95723033, 209.7179434 , 185.71531692, 147.23625586,
       150.40785093, 102.60018559, 170.78899034, 177.8219416 ,
       152.40388316, 187.08466299, 197.72314739, 204.83066546,
       132.09655487, 158.42112429, 260.54948673, 125.48180691,
       195.29165994, 125.76882485, 163.21646899,  58.37895843,
       158.14323269, 103.4034084 , 128.04980829, 161.3128156 ,
       146.00080757, 219.57659671, 126.64096152, 131.12134464,
       150.1627216 ,  92.3404223 , 120.10323463, 261.33608538,
       150.22171365, 197.82772808, 145.97361477, 104.56119742,
       139.47230609, 192.90101701, 159.2347891 , 135.21956019,
       120.30423162, 262.94731714, 255.46123067, 151.24338655,
       153.11282489, 128.59191597,  69.02540213, 136.99

In [54]:
r2_score(y_test,y_pred)

0.4161792211496944

<h1>For using formula we need to insert 1 in fornt of all row</h1>

In [26]:
np.insert(X_train,0,1,axis=1)

array([[ 1.        ,  0.06713621, -0.04464164, ..., -0.03949338,
        -0.0561531 , -0.05906719],
       [ 1.        , -0.05273755, -0.04464164, ..., -0.00259226,
        -0.02712902, -0.05078298],
       [ 1.        , -0.05273755, -0.04464164, ...,  0.03430886,
         0.13237579,  0.00306441],
       ...,
       [ 1.        , -0.01277963, -0.04464164, ...,  0.03430886,
         0.07020738,  0.00720652],
       [ 1.        , -0.03457486,  0.05068012, ...,  0.1081111 ,
         0.02671684,  0.07348023],
       [ 1.        ,  0.01991321,  0.05068012, ..., -0.00259226,
         0.00370906,  0.04034337]], shape=(353, 11))